openapi: 3.1.0
info:
  title: A minimal OpenAPI document
  version: 0.0.1
paths: {
  /model/{id}:
    get:
      summary: Get the model for the given id
      description: Retrieves the whole model for the given id
      parameters:
        - name: id
          in: path
          required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              type: object
              properties:
                model:
                  type: object
                  properties:
                    displayName:
                      type: string
                    tags:
                      type: array
    post:
      summary: Get the model for the given id
      description: Retrieves the whole model for the given id
    put:
      summary: Get the model for the given id
      description: Retrieves the whole model for the given id
    delete:
      summary: Get the model for the given id
      description: Retrieves the whole model for the given id
}