printConfig = false

[logging]
logFile = "testdata/.ymir/log/ymir.log"
logLevel="DEBUG"
stdOut = true
fileOut = false

[datastore]
dbFile="testdata/.ymir/ymir.db"

[models]
uploadsTempDir="testdata/.ymir/uploads/tmp"
modelsDir="testdata/.ymir/models"

[printers]
printersDir="testdata/.ymir/printers"

[http]
hostname = "localhost"
port = "8081"
usehttps = false
TLSMinVersion = "1.2"
HttpTLSStrictCiphers = false
TLSCert = "ymir.crt"
TLSKey = "ymir.key"
enableCORS = true
JWTSecret = "abc123"

[http.logging]
enabled = false
stdOut = true
fileOut = false
logFile = "testdata/.ymir/log/ymir_http.log"