printConfig = false

[logging]
logFile = "log/ymir.log"
logLevel="ERROR"

[db]
host = "localhost"
port = "5984"
username = "admin"
password = "password"
dbName = "ymir"

[models]
uploadsTempDir="uploads/tmp"
modelsDir="uploads/modelFiles"

[printer]
host="127.0.0.1"
type="Prusa Mk3S+"
apiType="octoprint"
apikey="ABC123"

[http]
hostname = "0.0.0.0"
port = "8081"
usehttps = false
TLSMinVersion = "1.2"
HttpTLSStrictCiphers = false
TLSCert = "ymir.crt"
TLSKey = "ymir.key"
enableCORS = true
JWTSecret = "abc123"

[http.logging]
enabled = true
stdout = false
fileout = true
logfile = "log/ymir_http.log"