printConfig = false

[logging]
logFile = "/var/log/ymir/ymir.log"
logLevel="INFO"
stdOut = true
fileOut = true

[datastore]
dbFile="/usr/lib/ymir/ymir.db"

[models]
uploadsTempDir="~/.ymir/uploads/tmp"
modelsDir="~/.ymir/models"

[printers]
printersDir="~/.ymir/printers"

[http]
hostname = "0.0.0.0"
port = "8081"
usehttps = false
TLSMinVersion = "1.2"
HttpTLSStrictCiphers = false
TLSCert = "ymir.crt"
TLSKey = "ymir.key"
enableCORS = true
JWTSecret = "abc123"

[http.logging]
enabled = true
stdOut = false
fileOut = true
logFile = "/var/log/ymir/ymir_http.log"